# Generated by Django 2.1.7 on 2019-03-22 16:53

from django.db import migrations, models
import sideproject.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=sideproject.utils.uuid_name_upload_to),
        ),
    ]
