# Generated by Django 2.1.7 on 2019-03-22 16:53

from django.db import migrations, models
import sideproject.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190322_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to=sideproject.utils.uuid_name_upload_to),
        ),
    ]
